### ISSUE TITLE
[Suggestion] Change default parameters (ICAO, lat, long)

### ISSUE THREAD

**Issue by sashatytko** [Matioupi/realtime-adsb-out#1]
Hello!
I really amazed about this repo and amount of work you have done to make it work. Actually, today I`ve started investigating ads-b out repo to add a callsign support but find out your twitter post and repo.

So my suggestion is to change the default parameters to avoid situation when someone accidentally forgets to set these parameters and start tx-ing to some flight tracking service. 
It`s important because Russia can use flight radar data falsely, adjusting some information as they want and need to justify theirs actions (ex. new attacks)

PS All Ukrainians (including goverement, pilots) say with confidence that AN-225 will be restored shortly after the war is over!

**Comment by Matioupi** [comment]
Hello, thank you for your suggestion. However I will not change the default ICAO hex code / position, it purposely default to Мрія as a tribute to this mythical plane that was destroyed by Putin dictator army.  Although we are leaving this nightmare right now with crazy information war and stupid "arguments" by Russian side officials, I don't think any military decisions will ever rely on such platforms information. This was one of the point with this project to demonstrate how easy it is to spoof.

Would live flight platforms want to harden the anti-spoofing game, they could easily start by filtering this hex code as the plane was destroyed in the first days of war.  Still people playing with the repo on their local computer would see the AN-225.

Just for the anecdote, I was lucky enough to see this plane when I was a kid, both on the ground and in flight carrying Бура́н. It was the first time I was attending Paris air show, back in 1989.
[Мрія at Paris air show 1989 (1)](https://www.buran.fr/bourane-buran/Photos/095-Le%20Bourget%201989-Le%20Bourget%201989-02.jpg)
[Мрія at Paris air show 1989 (2)](https://www.buran.fr/bourane-buran/Photos/095-Le%20Bourget%201989-Le%20Bourget%201989-04.jpg)
(photos not by me)
I remember it very well because I was wearing shorts. The morning weather was nice but turned cold and rainy in the afternoon. I was soaked and frozen and my parents wanted to leave while I was this 13 y.o boy almost crying to stay a bit longer and see more planes...

**Comment by sashatytko** [comment]
Appreciate and agree with your point of view!
